package dev.hugame.input;

public enum Key {

	NUM_0("0"),
	NUM_1("1"),
	NUM_2("2"),
	NUM_3("3"),
	NUM_4("4"),
	NUM_5("5"),
	NUM_6("6"),
	NUM_7("7"),
	NUM_8("8"),
	NUM_9("9"),
	A("A"),
	ALT_LEFT("L-Alt"),
	ALT_RIGHT("R-Alt"),
	APOSTOPHE("'"),
	AT("@"),
	B("B"),
	BACK("Back"),
	BACKSLASH("\\"),
	C("C"),
	CALL("Call"),
	CAMERA("Camera"),
	CAPS_LOCK("Caps Lock"),
	CLEAR("Clear"),
	COMMA(","),
	D("D"),
	DEL("Delete"),
	FORWARD_DEL("Forward Delete"),
	DPAD_CENTER("D-Pad Center"),
	DPAD_DOWN("D-Pad Down"),
	DPAD_LEFT("D-Pad Left"),
	DPAD_RIGHT("D-Pad Right"),
	DPAD_UP("D-Pad Up"),
	CENTER("Center"),
	DOWN("Down"),
	LEFT("Left"),
	RIGHT("Right"),
	UP("Up"),
	E("E"),
	END_CALL("End Call"),
	ENTER("Enter"),
	ENVELOPE("Envelope"),
	EQUALS("="),
	EXPLORER("Explorer"),
	F("F"),
	FOCUS("Focus"),
	G("G"),
	GRAVE("`"),
	H("H"),
	HEADSETHOOK("Headset Hook"),
	HOME("Home"),
	I("I"),
	J("J"),
	K("K"),
	L("L"),
	LEFT_BRACKET("["),
	M("M"),
	MEDIA_FAST_FORWARD("Fast Forward Media"),
	MEDIA_NEXT("Next Media"),
	MEDIA_PLAY_PAUSE("Play/Pause Media"),
	MEDIA_PREVIOUS("Previous Media"),
	MEDIA_REWIND("Rewind Media"),
	MEDIA_STOP("Stop Media"),
	MENU("Menu"),
	MINUS("-"),
	MUTE("Mute"),
	N("N"),
	NOTIFICATION("Notification"),
	NUM("Num"),
	O("O"),
	P("P"),
	PAUSE("Pause"),
	PERIOD("."),
	PLUS("+"),
	POUND("Pound"),
	POWER("Power"),
	PRINT_SCREEN("Print Screen"),
	Q("Q"),
	R("R"),
	RIGHT_BRACKET("]"),
	S("S"),
	SCROLL_LOCK("Scroll Lock"),
	SEARCH("Search"),
	SEMICOLON(";"),
	SHIFT_LEFT("L-Shift"),
	SHIFT_RIGHT("R-Shift"),
	SLASH("/"),
	SOFT_LEFT("Soft Left"),
	SOFT_RIGHT("Soft Right"),
	SPACE("Space"),
	STAR("*"),
	SYM("Sym"),
	T("T"),
	TAB("Tab"),
	U("U"),
	UNKNOWN("Unknown"),
	V("V"),
	VOLUME_DOWN("Volume Down"),
	VOLUME_UP("Volume Up"),
	W("W"),
	X("X"),
	Y("Y"),
	Z("Z"),
	META_ALT_LEFT_ON("Meta Alt Left On"),
	META_ALT_ON("Meta Alt On"),
	META_ALT_RIGHT_ON("Meta Alt Right On"),
	META_SHIFT_LEFT_ON("Meta Shift Left On"),
	META_SHIFT_ON("Meta Shift On"),
	META_SHIFT_RIGHT_ON("Meta Shift Right On"),
	META_SYM_ON("Meta Sym On"),
	CONTROL_LEFT("L-Ctrl"),
	CONTROL_RIGHT("R-Ctrl"),
	ESCAPE("Escape"),
	END("End"),
	INSERT("Insert"),
	PAGE_DOWN("Page Down"),
	PAGE_UP("Page Up"),
	PICTSYMBOLS("Pictsymbols"),
	SWITCH_CHARSET("Switch Charset"),
	BUTTON_CIRCLE("Circle Button"),
	BUTTON_A("A Button"),
	BUTTON_B("B Button"),
	BUTTON_C("C Button"),
	BUTTON_X("X Button"),
	BUTTON_Y("Y Button"),
	BUTTON_Z("Z Button"),
	BUTTON_L1("L1 Button"),
	BUTTON_R1("R1 Button"),
	BUTTON_L2("L2 Button"),
	BUTTON_R2("R2 Button"),
	BUTTON_THUMBL("Left Thumb"),
	BUTTON_THUMBR("Right Thumb"),
	BUTTON_START("Start"),
	BUTTON_SELECT("Select"),
	BUTTON_MODE("Mode"),
	NUMPAD_0("Numpad 0"),
	NUMPAD_1("Numpad 1"),
	NUMPAD_2("Numpad 2"),
	NUMPAD_3("Numpad 3"),
	NUMPAD_4("Numpad 4"),
	NUMPAD_5("Numpad 5"),
	NUMPAD_6("Numpad 6"),
	NUMPAD_7("Numpad 7"),
	NUMPAD_8("Numpad 8"),
	NUMPAD_9("Numpad 9"),
	NUMPAD_DIVIDE("Numpad /"),
	NUMPAD_MULTIPLY("Numpad *"),
	NUMPAD_SUBTRACT("Numpad -"),
	NUMPAD_ADD("Numpad +"),
	NUMPAD_DOT("Numpad ."),
	NUMPAD_COMMA("Numpad ,"),
	NUMPAD_ENTER("Numpad Enter"),
	NUMPAD_EQUALS("Numpad ="),
	NUMPAD_LEFT_PAREN("Numpad ("),
	NUMPAD_RIGHT_PAREN("Numpad )"),
	NUM_LOCK("Num Lock"),
	COLON(":"),
	F1("F1"),
	F2("F2"),
	F3("F3"),
	F4("F4"),
	F5("F5"),
	F6("F6"),
	F7("F7"),
	F8("F8"),
	F9("F9"),
	F10("F10"),
	F11("F11"),
	F12("F12"),
	F13("F13"),
	F14("F14"),
	F15("F15"),
	F16("F16"),
	F17("F17"),
	F18("F18"),
	F19("F19"),
	F20("F20"),
	F21("F21"),
	F22("F22"),
	F23("F23"),
	F24("F24");
	
	private final String name;
	
	private Key(String name) {
		this.name = name;
	}
	
	public String getName() {
		return name;
	}
	
}
