plugins {
    id 'java-library'
    id 'maven-publish'
    id 'com.diffplug.spotless' version '8.1.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

ext {
    lwjglVersion = '3.3.5'
    lwjglNatives = 'natives-windows'
}

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "io.semillita.hugame:hugame:0.0.1"

    implementation "io.semillita.hugame:hugame-desktop-vulkan:0.0.1"

    implementation "io.semillita.hugame:hugame-assimp:0.0.1"

    implementation "com.formdev:flatlaf:3.0"
    implementation "com.formdev:flatlaf-extras:3.0"

    implementation "tools.jackson.core:jackson-databind:3.0.3"

    annotationProcessor "org.projectlombok:lombok:1.18.42"
    compileOnly "org.projectlombok:lombok:1.18.42"

    implementation "org.lwjgl:lwjgl"
    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"

    implementation "org.lwjgl:lwjgl-nfd"
    runtimeOnly "org.lwjgl:lwjgl-nfd::$lwjglNatives"

    implementation("org.lwjglx:lwjgl3-awt:0.2.3") {
        exclude group: "org.lwjgl", module: "lwjgl"
    }
}

spotless {
    java {
        googleJavaFormat("1.25.2")
        trimTrailingWhitespace()
        endWithNewline()
        leadingTabsToSpaces(4)
    }
}

group = 'io.semillita.hugame'
version = '0.0.1'

publishing {
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}
