[versions]
lwjgl-version = "3.3.5"

[libraries]
flatlaf = { module = "com.formdev:flatlaf", version = "3.0" }
flatlaf-extras = { module = "com.formdev:flatlaf-extras", version = "3.0" }

lwjgl-nfd = { module = "org.lwjgl:lwjgl-nfd", version.ref = "lwjgl-version" }

jackson = { module = "tools.jackson.core:jackson-databind", version = "3.0.3" }

lombok = { module = "org.projectlombok:lombok", version = "1.18.42" }